### ISSUE TITLE
cart page

### ISSUE THREAD

**Issue by 0407chan** [woowa-techcamp-2020/bmart-9#52]
- 장바구니 페이지를 구현하자.

### 기본 화면 분석
<kbd> 
<img width="749" alt="장바구니 기본화면" src="https://user-images.githubusercontent.com/19217576/90641833-a1f8bd80-e26c-11ea-8412-f4b1622dabd5.png">
</kbd><br>

### Todo
- [ ] 헤더 고정하기
- [ ] 전체 선택 체크 시 모든 체크들 해제/선택
- [ ] 선택 비우기 시 popup, 선택된 애들 모두 삭제 할 거냐고 물어봄 yes시 check된애들 삭제 취소시 노 이벤트
- [ ] cart item 뿌려주기
- cart item api 만들기 
   - [ ] addToCart
   - [ ] deleteCartItem 
   - [ ] updateCartItem
   - [ ] getAllCartItem
- [ ] 주문 버튼
   - [ ] 버튼에 현재 장바구니 총 아이템 개수 표시
   - [ ] (선택) 클릭 시 결제 페이지로 이동 -> 카카오 페이 결제 연동해도 괜춘할듯
- [ ] 전체 장바구니 아이템 개수 가지고 있는 변수 필요할 듯 -> 메인화면 장바구니 아이콘에서도 필요함

### 장바구니 맨 아래 분석
<kbd>
<img width="655" alt="장바구니 맨 아래 화면" src="https://user-images.githubusercontent.com/19217576/90641802-9a391900-e26c-11ea-958f-128abccf4a36.png">
</kbd><br>

### Todo
- [ ] 더 담으러 가기 누르면 홈으로 돌아감
- [ ] 전체 금액 한번 더 보여줌 -> 여기에 총 할인 금액 이런거 보여줘도 될듯
- [ ] 스크롤 맨 아래로 내리면 추가 설명같은거 있음.
- [ ] 스크롤 맨 아래로 내렸을 때 주문 버튼 자리 있을정도로 height잡기

### 장바구니 비어있을 때
<kbd>
<img width="569" alt="장바구니 비었다" src="https://user-images.githubusercontent.com/19217576/90641805-9b6a4600-e26c-11ea-8f50-d1cdcc7ade0c.png">
</kbd><br>

### Todo
- [ ] 텅 이미지 넣기
- [ ] 그냥 없다고만 하면 아쉬우니가, 구매하러 가기 버튼 추가해줘도 될듯
    -> 뭔가 배민 감성으로 더 채우자, 더 구매하자, 더 장보자? 는 느낌의 위트를 추가해서 하면 더 좋을듯.

**Comment by naamoonoo** [comment]
이대로만 구현하면 개꿀각 
오늘 구현 됨?
